### PR TITLE
[idea] #299 New settings panel fixed to load values persisted by old …

### LINKED ISSUE #299: New Settings panel is honoring old settings and stuck with wrong values.
Result size is 0

image

### PR DESCRIPTION
**Pull request by keerath**
…settings panel

fixes #299

### CODE REVIEW

File: plugins/idea/kodebeagleidea/src/main/java/com/imaginea/kodebeagle/model/Settings.java [hunk 1]
```diff
@@ -312,6 +339,23 @@ public final void save() {
...
     }
 
+    private void setOldImportsAsPatternAndState(final String oldImports) {
+        PropertiesComponent propertiesComponent = PropertiesComponent.getInstance();
+        List<String> oldPatterns = new ArrayList<>();
+        List<String> oldStates = new ArrayList<>();
+            if (oldImports != null) {
+                List<String> oldImportsList = Arrays.asList(oldImports.split(DELIMITER));
+                for (String oldImport : oldImportsList) {
+                    oldPatterns.add(oldImport);
```
Comment (ScrapCodes) [inline plugins/idea/kodebeagleidea/src/main/java/com/imaginea/kodebeagle/model/Settings.java]: Apply trim() and skip string.isEmpty().

File: plugins/idea/kodebeagleidea/src/main/java/com/imaginea/kodebeagle/model/Settings.java [hunk 2]
```diff
@@ -109,18 +113,41 @@ private void save() {
...
-            this.setTopCount(Integer.parseInt(propertiesComponent.getValue(
+                    String.valueOf(RefreshAction.SIZE_DEFAULT_VALUE)));
+            int persistedTopCount = Integer.parseInt(propertiesComponent.getValue(
                     RefreshAction.TOP_COUNT,
-                    String.valueOf(RefreshAction.TOP_COUNT_DEFAULT_VALUE))));
+                    String.valueOf(RefreshAction.TOP_COUNT_DEFAULT_VALUE)));
+            if (isWithInLimits(persistedLinesFromCursor,
+                    LimitsPanel.LINES_FROM_CURSOR_MIN,
+                    LimitsPanel.LINES_FROM_CURSOR_MAX)) {
+                this.setLinesFromCursor(persistedLinesFromCursor);
```
Comment (ScrapCodes) [inline plugins/idea/kodebeagleidea/src/main/java/com/imaginea/kodebeagle/model/Settings.java]: instead of repeating this logic again and agina make a utility function and call it everywhere.
